# -*- coding: utf-8 -*-
#|create_2D

import pythoncom
from win32com.client import Dispatch, gencache

import LDefin2D
import MiscellaneousHelpers as MH

#  Подключим константы API Компас
kompas6_constants = gencache.EnsureModule("{75C9F5D0-B5B8-4526-8681-9903C567D2ED}", 0, 1, 0).constants
kompas6_constants_3d = gencache.EnsureModule("{2CAF168C-7961-4B90-9DA2-701419BEEFE3}", 0, 1, 0).constants

#  Подключим описание интерфейсов API5
kompas6_api5_module = gencache.EnsureModule("{0422828C-F174-495E-AC5D-D31014DBBE87}", 0, 1, 0)
kompas_object = kompas6_api5_module.KompasObject(Dispatch("Kompas.Application.5")._oleobj_.QueryInterface(kompas6_api5_module.KompasObject.CLSID, pythoncom.IID_IDispatch))
MH.iKompasObject  = kompas_object

#  Подключим описание интерфейсов API7
kompas_api7_module = gencache.EnsureModule("{69AC2981-37C0-4379-84FD-5DD2F3C0A520}", 0, 1, 0)
application = kompas_api7_module.IApplication(Dispatch("Kompas.Application.7")._oleobj_.QueryInterface(kompas_api7_module.IApplication.CLSID, pythoncom.IID_IDispatch))
MH.iApplication  = application


Documents = application.Documents
#  Открываем документ
kompas_document = Documents.Open("D:/WorkDirectory/Сборки/2/Сборка.a3d", True, False)

kompas_document_3d = kompas_api7_module.IKompasDocument3D(kompas_document)
iDocument3D = kompas_object.ActiveDocument3D()

#  Создаем новый документ
kompas_document = Documents.AddWithDefaultSettings(kompas6_constants.ksDocumentSpecification, True)

kompas_document_spc = kompas_api7_module.ISpecificationDocument(kompas_document)
iDocumentSpc = kompas_object.SpcActiveDocument()

#  Создаем новый документ
kompas_document = Documents.AddWithDefaultSettings(kompas6_constants.ksDocumentDrawing, True)

kompas_document_2d = kompas_api7_module.IKompasDocument2D(kompas_document)
iDocument2D = kompas_object.ActiveDocument2D()

iAssociationViewParam = kompas6_api5_module.ksAssociationViewParam(kompas_object.GetParamStruct(kompas6_constants.ko_AssociationViewParam))
iAssociationViewParam.Init()
iAssociationViewParam.disassembly = True
iAssociationViewParam.fileName = "D:\WorkDirectory\Сборки\2\Сборка.a3d"
iAssociationViewParam.hiddenLinesShow = False
iAssociationViewParam.hiddenLinesStyle = 4
iAssociationViewParam.projBodies = True
iAssociationViewParam.projectionLink = False
iAssociationViewParam.projectionName = "#Изометрия"
iAssociationViewParam.projSurfaces = False
iAssociationViewParam.projThreads = True
iAssociationViewParam.sameHatch = False
iAssociationViewParam.section = False
iAssociationViewParam.tangentEdgesShow = True
iAssociationViewParam.tangentEdgesStyle = 2
iAssociationViewParam.visibleLinesStyle = 1
iViewParam = kompas6_api5_module.ksViewParam(iAssociationViewParam.GetViewParam())
iViewParam.Init()
iViewParam.angle = 0
iViewParam.color = 0
iViewParam.name = "Вид 1"
iViewParam.scale_ = 1
iViewParam.state = 3
iViewParam.x = 106.211559585963
iViewParam.y = 160.814897674503
iDocument2D.ksCreateSheetArbitraryView(iAssociationViewParam, 0)
obj = iDocument2D.ksLayer(1)
iLayerParam = kompas6_api5_module.ksLayerParam(kompas_object.GetParamStruct(kompas6_constants.ko_LayerParam))
iLayerParam.Init()
iLayerParam.color = 12615680
iLayerParam.name = ""
iLayerParam.state = 3
iDocument2D.ksSetObjParam(obj, iLayerParam, LDefin2D.ALLPARAM)
iPosLeaderParam = kompas6_api5_module.ksPosLeaderParam(kompas_object.GetParamStruct(kompas6_constants.ko_PosLeaderParam))
iPosLeaderParam.Init()
iPosLeaderParam.arrowType = 1
iPosLeaderParam.dirX = -1
iPosLeaderParam.dirY = -1
iPosLeaderParam.style = 65535
iPosLeaderParam.x = -22.630004475654
iPosLeaderParam.y = -70.207259421637
iPolylineArray = kompas6_api5_module.ksDynamicArray(iPosLeaderParam.GetpPolyline())
iMathPointArray = kompas_object.GetDynamicArray(LDefin2D.POINT_ARR)
iMathPointParam = kompas6_api5_module.ksMathPointParam(kompas_object.GetParamStruct(kompas6_constants.ko_MathPointParam))
iMathPointParam.Init()
iMathPointParam.x = -12.630004475654
iMathPointParam.y = -5.921730155191
iMathPointArray.ksAddArrayItem(-1, iMathPointParam)
iPolylineArray.ksAddArrayItem(-1, iMathPointArray)
iPosLeaderParam.SetpPolyline(iPolylineArray)
iTextLineArray = kompas6_api5_module.ksDynamicArray(iPosLeaderParam.GetpTextline())

iTextLineParam = kompas6_api5_module.ksTextLineParam(kompas_object.GetParamStruct(kompas6_constants.ko_TextLineParam))
iTextLineParam.Init()
iTextLineParam.style = 5
iTextItemArray = kompas_object.GetDynamicArray(LDefin2D.TEXT_ITEM_ARR)
iTextItemParam = kompas6_api5_module.ksTextItemParam(kompas_object.GetParamStruct(kompas6_constants.ko_TextItemParam))
iTextItemParam.Init()
iTextItemParam.iSNumb = 0
iTextItemParam.s = "3"
iTextItemParam.type = 0
iTextItemFont = kompas6_api5_module.ksTextItemFont(iTextItemParam.GetItemFont())
iTextItemFont.Init()
iTextItemFont.bitVector = 4096
iTextItemFont.color = 0
iTextItemFont.fontName = "GOST type A"
iTextItemFont.height = 7
iTextItemFont.ksu = 1
iTextItemArray.ksAddArrayItem(-1, iTextItemParam)
iTextLineParam.SetTextItemArr(iTextItemArray)

iTextLineArray.ksAddArrayItem(-1, iTextLineParam)
iPosLeaderParam.SetpTextline(iTextLineArray)
iDocument2D.ksPositionLeader(iPosLeaderParam)
kompas_document.SaveAs(r"D:\WorkDirectory\Сборки\2\Сборка.cdw")
kompas_document.Save()
